-- R2DBC does not auto-create tables like JPA/Hibernate does.
-- This file is executed automatically by Spring Boot on startup.
CREATE TABLE IF NOT EXISTS tbl_product (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    price    DECIMAL(10, 2) NOT NULL,
    category VARCHAR(100)
);
